<?php

namespace Siteadmin3Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Siteadmin3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Siteadmin3Repository extends EntityRepository
{
}
